---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: packages

- name: install debian packages
  apt:
    name: "{{ packages_install }}"
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"
  environment: "{{ proxy_env }}"
  tags: packages
  become: true

- name: remove debian packages
  apt:
    name: "{{ packages_remove }}"
    state: absent
  when: ansible_os_family == "Debian"
  environment: "{{ proxy_env }}"
  tags: packages
  become: true

- name: install rhel packages
  yum:
    name: "{{ packages_install }}"
    state: present
  when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env }}"
  tags: packages
  become: true

- name: install rhel epel repo
  package:
    name: epel-release
    state: present
  environment: "{{ proxy_env }}"
  when: packages_epel_release and ansible_os_family == "RedHat"
  become: true
  tags: packages

- name: install rhel packages from epel repo
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_install_epel }}"
  environment: "{{ proxy_env }}"
  when: packages_epel_release and ansible_os_family == "RedHat"
  become: true
  tags: packages

- name: remove rhel packages
  yum:
    name: "{{ packages_remove }}"
    state: absent
  when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env }}"
  tags: packages
  become: true